// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
 
public class SampleAppScript: MonoBehaviour
{
	int width, height;
	float scalex,scaley;
	public GUIStyle centeredStyle;
	public GUIStyle buttonStyle;
	 
	public int reward=0;
	String app_key = "7eae9c2a62c171d4be9e53605d597eb99971e266";//Add your AppEngage App Key here";
	String getDeviceID="";

	void Start(){
		DontDestroyOnLoad(this);
		height= Screen.height;
		width= Screen.width;
		 
		scalex=((float)width)/1024;
		scaley=((float)height)/768;
	  
		centeredStyle.alignment = TextAnchor.UpperCenter;
		centeredStyle.fontStyle = FontStyle.Bold;
		centeredStyle.fontSize = 22;

		AppEngagePlugin.onCreate (app_key); //call once on startup
		this.getDeviceID = AppEngagePlugin.getDeviceID ();
		Debug.Log ("unityStart");
	}


	void OnGUI () {
		buttonStyle = GUI.skin.GetStyle ("Button");
		buttonStyle.fontSize = 19;
		int yPos = scaleY (50);


		GUI.Label (new Rect (0, scaleY (50), width, scaleY (100)), "AppEngage Sample App ", centeredStyle);

		//Show AppEngage Dialog
		yPos += scaleY (70);
		if (GUI.Button (new Rect (width * .1f, yPos, width * .8f, scaleY (100)), "Show AppEngage Dialog", buttonStyle)) {
			AppEngagePlugin.showAchievements ();
		}

		//complete AppEngage action
		yPos += scaleY (120);
		if (GUI.Button (new Rect (width * .1f, yPos, width * .8f, scaleY (100)), "Complete Action 'play'", buttonStyle)) {
			AppEngagePlugin.completeAction ("play");
		}

		yPos += scaleY (120);
		if (GUI.Button (new Rect (width * .1f, yPos, width * .8f, scaleY (100)), "Complete Action 'levelUp'", buttonStyle)) {
			AppEngagePlugin.completeAction ("levelUp");
		}

		//Quit app with proper AppEngage call
		yPos += scaleY (120);
		if (GUI.Button (new Rect (width * .1f, yPos, width * .8f, scaleY (100)), "Quit", buttonStyle)) {
			AppEngagePlugin.OnDestroy ();
			Application.Quit ();
		}
		yPos += scaleY (120);
		GUI.Label (new Rect (0, yPos, width, scaleY(100)), "Your Device ID = "+getDeviceID ,centeredStyle);

		yPos += scaleY (100);
		if (app_key.Contains ("Add your AppEngage")) {
			GUI.Label (new Rect (0, yPos, width, scaleY(100)), "Add your AppEngage app key to SampleAppScript" ,centeredStyle);
		}
		else if (reward>0)
			GUI.Label (new Rect (0, yPos, width, scaleY(100)), "User Reward ="+reward ,centeredStyle);
	}

	void OnApplicationPause(bool pauseStatus) {
		//Call AppEngage getPendingRewards when app resumes
		if (!pauseStatus) {
			reward=0;
			AppEngagePlugin.getPendingRewards ();
			Debug.Log ("OnApplicationPause");
		}
	}

	int scaleX(int x){
		return ((int) (x*scalex));
	}
	int scaleY(int y){
		return ((int) (y*scaley));
	}


}
 

